force-app/main/default/objects/AccountAudit__c/AccountAudit__c.object-meta.xml
<CustomObject>
    <label>AccountAudit</label>
    <nameField>
        <displayFormat>AD-{0000}</displayFormat>
        <label>Account Audit Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AccountAudits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AccountAudit__c/fields/Account_Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Account_Record_Id__c</fullName>
    <label>Account Record Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AccountAudit__c/fields/Record_JSON__c.field-meta.xml
<CustomField>
    <fullName>Record_JSON__c</fullName>
    <label>Record JSON</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/AccountAuditUtil.cls
public  without sharing class AccountAuditUtil {
    public static void saveAudit(string id) {
        // Not checking CRUD or field level permissions here on purpose.
        // Audit requirements are to save all specified data from record
        Account a = [select id, name, site from account where id = :id limit 1];

        AccountAudit__c accountAudit = new AccountAudit__c();
        accountAudit.Account_Record_Id__c = a.id;
        // this serialization approach is lazy and could be improved to 
        // create a string with only the field values needed for audit
        accountAudit.Record_JSON__c = JSON.serialize(a);
        
        insert as system accountAudit;
    }
}